### ISSUE TITLE
4.2.0版本在用GraalVM时与HikariCP的兼容问题

### ISSUE THREAD

**Issue by tuhe32** [baomidou/dynamic-datasource#597] opened 2023-11-27 09:13 UTC
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

Version info: 'GraalVM 22.3.0 Java 17 CE'
 Java version info: '17.0.5+8-jvmci-22.3-b08'
 C compiler: cc (apple, x86_64, 13.1.6)

JDK Version(required): 
 '17.0.5+8-jvmci-22.3-b08'
SpringBoot Version(required): 
3.1.4
dynamic-datasource-spring-boot-starter Version(required):
4.2.0
druid Version(optional):

# Describe what happened
项目用了HikariCP连接池
用mvn -Pnative clean native:compile 打包是成功的。启动报错：

Expected Result:

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.1.4)

2023-11-27T17:01:08.956+08:00  INFO 88353 --- [           main] c.e.bootnative.BootNativeApplication     : Starting AOT-processed BootNativeApplication using Java 17.0.5 with PID 88353 (/Users/liubin/work/projects/boot-native/target/boot-native started by liubin in /Users/liubin/work/projects/boot-native)
2023-11-27T17:01:08.956+08:00  INFO 88353 --- [           main] c.e.bootnative.BootNativeApplication     : No active profile set, falling back to 1 default profile: "default"
2023-11-27T17:01:08.971+08:00  INFO 88353 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'spring.datasource.dynamic-com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceProperties' of type [com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-11-27T17:01:08.971+08:00  INFO 88353 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceAopConfiguration' of type [com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceAopConfiguration$$SpringCGLIB$$0] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-11-27T17:01:08.972+08:00  WARN 88353 --- [           main] c.b.d.d.support.DataSourceClassResolver  : Failed to init mybatis-plus support.
2023-11-27T17:01:08.972+08:00  INFO 88353 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'dsProcessor' of type [com.baomidou.dynamic.datasource.processor.DsJakartaHeaderProcessor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-11-27T17:01:09.006+08:00  INFO 88353 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2023-11-27T17:01:09.007+08:00  INFO 88353 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-11-27T17:01:09.007+08:00  INFO 88353 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.13]
2023-11-27T17:01:09.020+08:00  INFO 88353 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-11-27T17:01:09.020+08:00  INFO 88353 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 64 ms
2023-11-27T17:01:09.034+08:00  WARN 88353 --- [           main] w.s.c.ServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'run': Unsatisfied dependency expressed through method 'run' parameter 0: Error creating bean with name 'bootNativeApplication.MyMapper': Cannot resolve reference to bean 'sqlSessionTemplate' while setting bean property 'sqlSessionTemplate'
2023-11-27T17:01:09.034+08:00  INFO 88353 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2023-11-27T17:01:09.035+08:00 ERROR 88353 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'run': Unsatisfied dependency expressed through method 'run' parameter 0: Error creating bean with name 'bootNativeApplication.MyMapper': Cannot resolve reference to bean 'sqlSessionTemplate' while setting bean property 'sqlSessionTemplate'
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveArgument(BeanInstanceSupplier.java:317) ~[na:na]
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveArguments(BeanInstanceSupplier.java:260) ~[na:na]
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:200) ~[na:na]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.obtainInstanceFromSupplier(DefaultListableBeanFactory.java:947) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1214) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1158) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[boot-native:6.0.12]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942) ~[boot-native:6.0.12]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608) ~[boot-native:6.0.12]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[boot-native:3.1.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) ~[boot-native:3.1.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439) ~[boot-native:3.1.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[boot-native:3.1.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) ~[boot-native:3.1.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) ~[boot-native:3.1.4]
	at com.example.bootnative.BootNativeApplication.main(BootNativeApplication.java:23) ~[boot-native:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bootNativeApplication.MyMapper': Cannot resolve reference to bean 'sqlSessionTemplate' while setting bean property 'sqlSessionTemplate'
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:377) ~[na:na]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:135) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1682) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:597) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:910) ~[na:na]
	at org.springframework.beans.factory.support.RegisteredBean.resolveAutowiredArgument(RegisteredBean.java:229) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveArgument(BeanInstanceSupplier.java:314) ~[na:na]
	... 21 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataSourceScriptDatabaseInitializer': Unsatisfied dependency expressed through method 'dataSourceScriptDatabaseInitializer' parameter 0: Error creating bean with name 'dataSource': com.zaxxer.hikari.HikariConfig.<init>()
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveArgument(BeanInstanceSupplier.java:317) ~[na:na]
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveArguments(BeanInstanceSupplier.java:260) ~[na:na]
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:200) ~[na:na]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.obtainInstanceFromSupplier(DefaultListableBeanFactory.java:947) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1214) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1158) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:312) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:365) ~[na:na]
	... 36 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource': com.zaxxer.hikari.HikariConfig.<init>()
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:910) ~[na:na]
	at org.springframework.beans.factory.support.RegisteredBean.resolveAutowiredArgument(RegisteredBean.java:229) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveArgument(BeanInstanceSupplier.java:314) ~[na:na]
	... 50 common frames omitted
Caused by: java.lang.NoSuchMethodException: com.zaxxer.hikari.HikariConfig.<init>()
	at java.base@17.0.5/java.lang.Class.getConstructor0(DynamicHub.java:3585) ~[boot-native:na]
	at java.base@17.0.5/java.lang.Class.getDeclaredConstructor(DynamicHub.java:2754) ~[boot-native:na]
	at com.baomidou.dynamic.datasource.toolkit.ConfigMergeCreator.create(ConfigMergeCreator.java:53) ~[na:na]
	at com.baomidou.dynamic.datasource.creator.hikaricp.HikariDataSourceCreator.createDataSource(HikariDataSourceCreator.java:75) ~[boot-native:na]
	at com.baomidou.dynamic.datasource.creator.DefaultDataSourceCreator.createDataSource(DefaultDataSourceCreator.java:97) ~[boot-native:na]
	at com.baomidou.dynamic.datasource.provider.AbstractDataSourceProvider.createDataSourceMap(AbstractDataSourceProvider.java:53) ~[boot-native:na]
	at com.baomidou.dynamic.datasource.provider.YmlDynamicDataSourceProvider.loadDataSources(YmlDynamicDataSourceProvider.java:53) ~[boot-native:na]
	at com.baomidou.dynamic.datasource.DynamicRoutingDataSource.afterPropertiesSet(DynamicRoutingDataSource.java:231) ~[boot-native:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1817) ~[boot-native:6.0.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766) ~[boot-native:6.0.12]
	... 62 common frames omitted
```

```
Just paste your stack trace here!
```

# Steps to reproduce
测试用例：
- Step 1 
测试用例地址
https://github.com/tuhe32/boot-native.git

- Step 2 

- Step 3

**Comment by huayanYu** [comment] 2023-11-28 05:59
mvn -Pnative clean native:compile  跑不起来, 看异常感觉和classLoader有关...先自己排查看下也

**Comment by linghengqian** [comment] 2023-11-28 07:16
- Can you create a git of this zip at github.com so I can verify it via codespaces?

**Comment by tuhe32** [comment] 2023-11-28 08:10
> * https://github.com/tuhe32/boot-native.git

测试用例已经放到 git 上。
mvn -Pnative clean native:compile 是成功的。
启动项目时报错。

**Comment by tuhe32** [comment] 2023-11-28 08:12
> * Can you create a git of this zip at github.com so I can verify it via codespaces?
> * Please format your Error Log via markdown, which seems to be missing HikariCP’s GraalVM Reachability Metadata.

测试用例已经放到 git 上。https://github.com/tuhe32/boot-native.git
mvn -Pnative clean native:compile 是成功的。
启动项目时报错。

**Comment by linghengqian** [comment] 2023-11-28 11:48
- @tuhe32 Handled at https://github.com/linghengqian/boot-native/commit/a58b8d91008aef1a62787795e2de5da90a6f7714 .

- It seems you don't know how to use `org.springframework.boot:spring-boot-maven-plugin` -- so I refactored the `pom.xml` and created two Maven Profile of `nativeTest` and `generateMetadata` to directly expose the Error Log.

- You are using `org.graalvm.sdk:graal-sdk` at the classpath level, which is very dangerous behavior because the API of `graal-sdk` is not stable and its public API is usually used for Maven Plugin/Gradle Plugin/sbt Plugin. Please directly use JSON to define GraalVM Reachability Metadata, or use the relevant classes of Spring Framework to complete the definition of GraalVM Reachability Metadata. This additionally results in a buildArg that requires `-H:+AllowDeprecatedBuilderClassesOnImageClasspath`.
- This appears to be a bug involving `com.baomidou.mybatisplus.core.toolkit.LambdaUtils`. What I mean is that Mybatis Plus doesn't seem to work under GraalVM Native Image. This commit also exposes that the Dynamic Datasource may be missing some JSON entries, but because of the issues with Mybatis Plus, I don't see the need to try to submit a PR. 
- Call @huayanYu , it looks like you are a committer for Mybatis Plus, do you have any more information?
```shell
Caused by: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: java.lang.ClassNotFoundException: com.example.bootnative.BootNativeApplication$$Lambda$0e4dae6cce3633a42432312a352810f4c99affcf
       com.baomidou.mybatisplus.core.toolkit.support.SerializedLambda.extract(SerializedLambda.java:58)
       com.baomidou.mybatisplus.core.toolkit.LambdaUtils.extract(LambdaUtils.java:67)
       com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.getColumnCache(AbstractLambdaWrapper.java:128)
       com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.columnToString(AbstractLambdaWrapper.java:66)
       com.baomidou.mybatisplus.core.conditions.AbstractLambdaWrapper.lambda$columnsToString$0(AbstractLambdaWrapper.java:57)
       [...]
```

**Comment by linghengqian** [comment] 2023-11-28 12:18
- Fixed in https://github.com/linghengqian/boot-native/commit/50b6def6b93b8e43663f563469ffa2669286e185 , I just noticed `com.example.bootnative.LambdaRegistrationFeature`.🤣 I still would not encourage carrying GraalVM Feature classes on the classpath. This is very dangerous behavior with new versions of the GraalVM compiler.

- In the reproduced git, I did not write additional `extra-filter.json` to filter the third-party library JSON. You can refer to https://github.com/baomidou/dynamic-datasource/blob/v4.2.0/native-image/extra-filter.json.

- It looks like there are some JSON entries available for adding on the baomidou/dynamic-datasource side. @huayanYu Please assign this issue to me.

**Comment by linghengqian** [comment] 2023-11-28 12:44
- @tuhe32 I remove your custom graalvm featrue class via JSON at https://github.com/linghengqian/boot-native/commit/89737888e2cc7a18d6b8d8b53995a02f5ccbf34e. Using graal-sdk is completely unreasonable, it shouldn't be on the classpath. `lambdaCapturingTypes` sets the GraalVM Reachability Metadata specific to your project. This seems to involve a bug in `GraalVM CE 23.1.1 For JDK 21.0.1/GraalVM Tracing Agent`, which does not collect the contents of `lambdaCapturingTypes`.

**Comment by linghengqian** [comment] 2023-11-28 15:59
- So I confirmed the real missing GraalVM Reachability Metadata at https://github.com/linghengqian/boot-native/commit/34ff8ce857b09e3993be5bf414878e5b11291089. This question comes from https://github.com/oracle/graalvm-reachability-metadata/blob/0.3.5/metadata/com.zaxxer/HikariCP/5.0.1/reflect-config.json , not baomidou/dynamic-datasource .
```json
[
  {
    "condition":{"typeReachable":"com.zaxxer.hikari.HikariConfig"},
    "name":"com.zaxxer.hikari.HikariConfig",
    "methods":[{"name":"<init>","parameterTypes":[] }]
  }
]
```
- @tuhe32 I think you should open a related issue and PR at https://github.com/oracle/graalvm-reachability-metadata and provide a smaller unit test.

- I don't think baomidou/dynamic-datasource should actively host HikariCP's GraalVM Reachability Metadata unless many people ask for it. @huayanYu What do you think?

- This issue can be closed.

**Comment by huayanYu** [comment] 2023-11-29 01:46
说实话,我完全不了解GraalVM.... mybatis-plus支持springboot3的相关issue https://github.com/baomidou/mybatis-plus/issues/5527

**Comment by linghengqian** [comment] 2023-11-29 04:07
- There is a factual error in https://github.com/baomidou/mybatis-plus/issues/5527#issuecomment-1758863971 , user should use JSON definition instead of introducing `org.graalvm.sdk:graal-sdk`, `graal-sdk  `has been refactored starting with GraalVM 23.1.0, which means earlier versions of `graal-sdk` are completely obsolete.

- The behavior of defining GraalVM Reachability Metadata for Mybatis through code does not involve conditional entries, which does not meet the requirements of GraalVM Reachability Metadata, which means that this class is incomplete in class introspection.

- But in general, the current issue only concerns the missing GraalVM Reachability Metadata of HikariCP, which has nothing to do with Dynamic Datasource.

**Comment by wssy001** [comment] 2023-11-29 05:49
> * There is a factual error in [SpringBoot3支持问题 mybatis-plus#5527 (comment)](https://github.com/baomidou/mybatis-plus/issues/5527#issuecomment-1758863971) , user should use JSON definition instead of introducing `org.graalvm.sdk:graal-sdk`, `graal-sdk  `has been refactored starting with GraalVM 23.1.0, which means earlier versions of `graal-sdk` are completely obsolete.
> * The behavior of defining GraalVM Reachability Metadata for Mybatis through code does not involve conditional entries, which does not meet the requirements of GraalVM Reachability Metadata, which means that this class is incomplete in class introspection.
> * But in general, the current issue only concerns the missing GraalVM Reachability Metadata of HikariCP, which has nothing to do with Dynamic Datasource.

@linghengqian 
`Tracing Agent`无法搜集到`lambdaCapturingTypes`，而`Spring`团队不大算提供这方面的支持，貌似还觉得没必要。所以才不得已地引入`graal-sdk`， 属实是无奈之举

**Comment by wssy001** [comment] 2023-11-29 05:57
> * There is a factual error in [SpringBoot3支持问题 mybatis-plus#5527 (comment)](https://github.com/baomidou/mybatis-plus/issues/5527#issuecomment-1758863971) , user should use JSON definition instead of introducing `org.graalvm.sdk:graal-sdk`, `graal-sdk  `has been refactored starting with GraalVM 23.1.0, which means earlier versions of `graal-sdk` are completely obsolete.
> * The behavior of defining GraalVM Reachability Metadata for Mybatis through code does not involve conditional entries, which does not meet the requirements of GraalVM Reachability Metadata, which means that this class is incomplete in class introspection.
> * But in general, the current issue only concerns the missing GraalVM Reachability Metadata of HikariCP, which has nothing to do with Dynamic Datasource.

@linghengqian   引入 `graal-sdk` 纯属是无奈之举   正如你前文提及的，`Tracing Agent`无法收集到`lambdaCapturingTypes`内容；而且`Spring`团队也不重视，之前有开发者提了`feat`，要求完整适配`graal-sdk`中`org.graalvm.nativeimage.hosted.RuntimeSerialization#registerLambdaCapturingClass`这一方法，结果还被当成了无意义提案。

**Comment by linghengqian** [comment] 2023-11-29 06:04
> @linghengqian   引入 `graal-sdk` 纯属是无奈之举   正如你前文提及的，`Tracing Agent`无法收集到`lambdaCapturingTypes`内容；而且`Spring`团队也不重视，之前有开发者提了`feat`，要求适配`graal-sdk`中`org.graalvm.nativeimage.hosted.RuntimeSerialization#registerLambdaCapturingClass`这一方法，结果还被当成了无意义提案。

- @wssy001 There is also no reason to use graal-sdk, I demonstrated it at https://github.com/linghengqian/boot-native/commit/89737888e2cc7a18d6b8d8b53995a02f5ccbf34e .  Users only need to define json. 

```json
{
  "types":[
  ],
  "lambdaCapturingTypes":[
    {
      "name":"com.example.bootnative.BootNativeApplication"
    }
  ],
  "proxies":[
  ]
}
```

**Comment by huayanYu** [comment] 2023-11-29 07:01
所以和动态数据源无关是吧.

**Comment by linghengqian** [comment] 2023-11-29 07:06
> 所以和动态数据源无关是吧.

- This issue has nothing to do with dynamic datasource unless we host the GraalVM Reachability Metadata of a third-party library like shardingsphere. Reference https://github.com/apache/shardingsphere/tree/3aff42fbe6909674d7582e098c9c1a453a63e86d/infra/reachability-metadata/src/main/resources/META-INF/native-image .
- The JSON for these third-party libraries is more suitable for submission to https://github.com/oracle/graalvm-reachability-metadata . Users can add it by themselves.

**Comment by huayanYu** [comment] 2023-11-30 02:01
不明觉厉,closed.

**Closed by huayanYu** 2023-11-30 02:01 UTC

**Comment by bob266** [comment] 2023-12-08 09:41
> > 所以和动态数据源无关是吧.
> 
> * This issue has nothing to do with dynamic datasource unless we host the GraalVM Reachability Metadata of a third-party library like shardingsphere. Reference https://github.com/apache/shardingsphere/tree/3aff42fbe6909674d7582e098c9c1a453a63e86d/infra/reachability-metadata/src/main/resources/META-INF/native-image .
> * The JSON for these third-party libraries is more suitable for submission to https://github.com/oracle/graalvm-reachability-metadata . Users can add it by themselves.

在你的例子里面,可以跑起来,但是我要如何在编译的时候不报错呢

**Comment by linghengqian** [comment] 2023-12-08 12:25
> > > 所以和动态数据源无关是吧.
> > 
> > * This issue has nothing to do with dynamic datasource unless we host the GraalVM Reachability Metadata of a third-party library like shardingsphere. Reference https://github.com/apache/shardingsphere/tree/3aff42fbe6909674d7582e098c9c1a453a63e86d/infra/reachability-metadata/src/main/resources/META-INF/native-image .
> > * The JSON for these third-party libraries is more suitable for submission to https://github.com/oracle/graalvm-reachability-metadata . Users can add it by themselves.
> 
> 在你的例子里面,可以跑起来,但是我要如何在编译的时候不报错呢
> 

- @bob266 So my example proves that the error has nothing to do with Dynamic DataSource, but where is your example?

**Comment by 8502596** [comment] 2025-04-12 01:16
@linghengqian    我在你修改的项目基础上   通过以下测试   有一些疑惑 ，希望给看一下 [linghengqian-scratches/boot-native](https://github.com/linghengqian-scratches/boot-native)  通过您修改的项目 

下面是我的 demo   [boot-native demo](https://github.com/8502596/boot-native)   主要是想让  项目打包成   native  可执行文件  exe

但是 我发现  我的另一个项目 他无法从配置文件 yml 中读取   dynamic-datasource  的相关配置，无法通过  spring-boot  process-aot

报错的片段如下  

![Image](https://github.com/user-attachments/assets/bfa600d1-3fdc-40a9-a366-4b3407b61e10)

因为  maven  测试断点不起作用  我也不知道如何一步步查找问题所在 ，所以只能将  dynamic-datasource-spring-boot3-starter 的源码 加载进项目   使用 system.out.println 进行测试

![Image](https://github.com/user-attachments/assets/939a710d-3697-4d33-9a63-b61a9565d25c)


正常运行  不使用 spring  boot  aot  process  输出为

![Image](https://github.com/user-attachments/assets/acc592e6-2249-4af6-b1e6-a8cf94ac005c)


使用  spring  boot  aot  process  输出为 

![Image](https://github.com/user-attachments/assets/2e0b7f21-c437-4a97-a30a-52d1c37d0301)

可以很明显的看到   spring  boot  aot  无法读取  yml 文件的配置到配置类  即  DynamicDataSourceProperties  并没有被 

初始化后被正常的注入  

![Image](https://github.com/user-attachments/assets/9517c2bc-e801-42b2-8784-ea40197f4505)


一开始  我以为是  DynamicDataSourceProperties  注入的时候出错  所以使用了简单的  配置类进行注入测试

发现 spring  boot  aot  process 也不能正常取到值 

![Image](https://github.com/user-attachments/assets/4edacd6d-3487-4700-8334-f423f9bd9e84)


&  我的另一个项目   我还没有上传   使用mybatis-plus   dynamic-datasource   alibaba druid

正常运行  不使用 spring  boot  aot  process  输出为

![Image](https://github.com/user-attachments/assets/1d361013-e013-4688-bd53-17b121172866)

![Image](https://github.com/user-attachments/assets/ef3e89c7-1cfd-46af-8dc2-20bdd840478f)

![Image](https://github.com/user-attachments/assets/807a6971-0e8e-48fb-97d4-f35451818f00)

使用  spring  boot  aot  process  输出为 
![Image](https://github.com/user-attachments/assets/ab45f66b-518c-4861-9b2d-32cb393c5c7e)


这使我非常非常的困惑，spring aot  需要配置  reflect-config.json  等等

但我不知道 如何编写  而且 2个项目   [boot-native demo](https://github.com/8502596/boot-native)    和我另一个项目  的文件是一样的

![Image](https://github.com/user-attachments/assets/5df72b56-2d41-464a-a2e5-e29b98c85535)

**Comment by linghengqian** [comment] 2025-04-12 01:19
- @8502596 You should open a new issue, there is no point in replying to the old one.
- I don't think it's a good idea to copy large sections of the GraalVM documentation in your issue. You're asking about things that are already in the documentation.
